apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-service
  namespace: counter-service
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: counter-service
        image: 920373021859.dkr.ecr.eu-west-1.amazonaws.com/ze_my_ecr:2051a1fa12576faaa05a071d3fb10db66d10e588