apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-service
  namespace: counter-service
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: counter-service
        image: 920373021859.dkr.ecr.eu-west-1.amazonaws.com/ze_my_ecr:91dd32ec66e1e6675a592fd198f0d2290316a76d