apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.appName }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: {{ .Values.loadBalancer.eipAllocation }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.appName }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
