apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-service
  namespace: counter-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-service
  template:
    metadata:
      labels:
        app: counter-service
    spec:
      containers:
        - name: counter-service
          image: 920373021859.dkr.ecr.eu-west-1.amazonaws.com/ze_my_ecr:ba4fffe9ebe804edf26bc65f3bb8f5ced7c4bed7
          envFrom:
            - configMapRef:
                name: counter-service-config
          ports:
            - containerPort: 8080
              protocol: TCP
