apiVersion: v1
kind: Service
metadata:
  name: counter-service
  namespace: counter-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: counter-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80