apiVersion: v1
kind: Service
metadata:
  name: counter-service
  namespace: counter-service
spec:
  type: LoadBalancer
  selector:
    app: counter-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80