apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "counter-service-app"
  namespace: argocd
spec:
  project: default
  destination:
    namespace: counter-service-app
    server: https://kubernetes.default.svc
  source:
    helm:
      releaseName: counter-service-app
      version: v3
      valueFiles:
        - values.yaml
    path: live/dev/eu-west-1/counter-service-app
    repoURL: git@github.com:edgaroviz/devops-infra
    targetRevision: argo-app-fix
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true