apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "counter-service"
  namespace: argocd
spec:
  project: default
  destination:
    namespace: counter-service
    server: https://kubernetes.default.svc
  source:
    path: live/prod/eu-west-1
    repoURL: git@github.com:edgaroviz/devops-infra
    targetRevision: master
    # kustomize:
    #   namePrefix: counter-service-
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
