replicaCount: "1"
env: "dev"
image:

  tag: "00352468d45a445bf56dc222cd496a6090826c2b"
  repository-uri: "920373021859.dkr.ecr.eu-west-1.amazonaws.com/ze-my-ecr"

resources:
  requests:
    memory: "500Mi"
    cpu: "500m"
  limits:
    memory: "1GB"
    cpu: "1"