replicaCount: "1"
environment: "dev"
image:
  tag: "c73474f6da05b5abd88907cca8ffb7981d651c45"
  repository-uri: "920373021859.dkr.ecr.eu-west-1.amazonaws.com/ze_my_ecr"
resources:
  requests:
    memory: "500Mi"
    cpu: "500m"
  limits:
    memory: "1GB"
    cpu: "1"
