replicaCount: "1"
environment: "dev"
image:
  tag: "c37a59c9516c229f089ce5d5db499562634e5576"
  repository-uri: "920373021859.dkr.ecr.eu-west-1.amazonaws.com/ze-my-ecr"
resources:
  requests:
    memory: "500Mi"
    cpu: "500m"
  limits:
    memory: "1GB"
    cpu: "1"
