replicaCount: "1"
env: "dev"
image:
  tag: "latest"
  repository-uri: "920373021859.dkr.ecr.eu-west-1.amazonaws.com/ze-my-ecr"

resources:
  requests:
    memory: "500Mi"
    cpu: "500m"
  limits:
    memory: "1GB"
    cpu: "1"


