name: Create App Infra 

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  Terraform-init-validate-plan-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::920373021859:role/ze-my-admin-role
          aws-region: eu-west-1
          role-session-name: APIActions
          role-duration-seconds: 3600

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5

      - name: Terraform infra init, validate for all environments and regions
        run: |
          for env in tf-infra/env/*; do
            echo "Terraform init, valite and plan in $env"
            for region in "$env"/*; do
              terraform -chdir=$region/infra init
              terraform -chdir=$region/infra validate
              echo "Initialized and validated changes at region: $region"
            echo "Initialized and validated changes at envrionemnt: $env"
            done
          done

      - name: Terraform infra apply for all environments and regions
        run: |
          for env in tf-infra/env/*; do
            echo "Terraform plan in $env"
            for region in "$env"/*; do
              terraform -chdir=$region/infra apply -auto-approve
              echo "Applied changes at region: $region"
            echo "Applied changes at environment: $env"
            done
          done

  # manual-approval:
  #   name: Manual Approval
  #   runs-on: ubuntu-latest
  #   needs: Terraform-init-validate-plan
  #   if: always()
    
  #   permissions:
  #     issues: write

  #   steps:
  #     - name: Await Manual Approval
  #       uses: trstringer/manual-approval@v1
  #       with:
  #         secret: ${{ github.TOKEN }}
  #         approvers: edgaroviz
  #         minimum-approvals: 1
  #         issue-title: "Manual Approval Required for Terraform Apply"
  #         issue-body: "Please approve or deny the deployment."

  Argo_installation:
    needs: [Terraform-init-validate-plan-apply]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::920373021859:role/ze-my-admin-role
          aws-region: eu-west-1
          role-session-name: APIActions
          role-duration-seconds: 3600

      - uses: azure/setup-helm@v4.2.0
        with:
          version: 'latest'

      - name: Deploy ArgoCD
        run: |
          helm repo add argo https://argoproj.github.io/argo-helm
          for env in $(ls tf-infra/env); do
            echo "Adding ${env} to kube config and installing ArgoCD"
            aws eks --region eu-west-1 update-kubeconfig --name ze-$env-eu-west-1-eks --kubeconfig ~/.kube/config
            helm upgrade argocd-$env argo/argo-cd -f argocd-values/argocd-values.yaml --namespace argocd --create-namespace --install
          done

      - name: Attach repo to ArgoCD
        run: |
          if kubectl get secret argocd-devops-infra-repo --namespace argocd &> /dev/null; then
            echo "Secret already exists, skipping creation."
          else
            kubectl create secret generic argocd-counter-service-repo \
              --namespace argocd \
              --from-literal=url=https://github.com/edgaroviz/devops-infra.git \
              --from-literal=username=argocd-private-repo \
              --from-literal=password=${{ secrets.PAT_GITHUB }} \
              --type Opaque
            kubectl label secret argocd-counter-service-repo -n argocd argocd.argoproj.io/secret-type=repository --overwrite
          fi
